import RequestCard from '@/components/cards/request_cards'
import CLMain from '@/components/cards_library/cards_library'
import Head from 'next/head'

export default function Card_Library() {
  return (
    <>
      <Head>
        <title>MTG Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RequestCard/>
      <CLMain/>
    </>
  )
}
