import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import SlidershowMain from '@/components/slideshow/slideshowMain'
// import { useState, useEffect } from 'react';
import magicDeck from '@/assets/magicDeck.png'
import Vraska from '@/assets/vraska.webp'
import mm_im1 from '@/assets/mm_im1.webp'
import ExampleCard from '@/assets/ex_card1.jpg'
import Link from 'next/link'
import Card from '@/components/cards/card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  // const [backgroundSize, setBackgroundSize] = useState(150);
  // const [opacity, setOpacity] = useState(1);

  // const handleScroll = () => {
  //   setBackgroundSize(150 - window.pageYOffset/12);
  //   setOpacity(1 - window.pageYOffset/700);
  // };

  // // Add an event listener for scrolling when the component mounts
  // useEffect(() => {
  //   window.addEventListener('scroll', handleScroll);
  //   return () => {
  //     window.removeEventListener('scroll', handleScroll);
      
  //   };
  // }, []);


  return (
    <>
      <Head>
        <title>MTG Collection </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className='slidershow' id="slideshow" style={{ backgroundSize: `${backgroundSize}%`, opacity: opacity}}/> */}
      <SlidershowMain text='MTG The Collection'/>
      <section className='main-section'>
        <div className='section-box col-g-12'>
          <div className='section-box-top'>
            <h1>The Collection</h1>
          </div>
          <div className='section-box-bottom'>
            <div className='bb-left'>
              <Image src={magicDeck} className='bb-left-im'/>
            </div>
            <div className='bb-right'>
              <div className='bb-right-top'>
                <p>The Multiverse of Magic: The Gathering is a shifting space of unique, disconnected worlds, called planes. The Blind Eternities between those worlds are unknown and impenetrable to the artifice of most cultures, but can be freely traveled by rare individuals, planeswalkers, who possess an intrinsic spark that frees them from ordinary limits. The stories of the Multiverse span millennia and numerous planes.</p>
              </div>
              <div className='bb-right-bottom'>
                <Link href={"/what-is-mtg"}><input type="button" className='button-main' value={`What's MTG`}/></Link>       
                <Link href={"/cards-library"}><input type="button" className='button-main' value={`Cards Library`}/></Link>
              </div>
            </div>
          </div>
        </div>
        <div className='quote-section'>
          <div className='quote-text-box'><p>"My past is part of who I am, but it is not who I am." — Vraska, later Jace</p></div>
          <div className='quote-im-box'><Image src={Vraska} className='quote-im-box-im'/></div>
        </div>

      </section>
      <div className='multi-menu col-g-12'>  
          <div className='mm-bg'></div>
          <div className='mm-textbox'>
            <Link target="_blank" href="https://magic.wizards.com/en">
              <div className='mm-imbox'>
                <Image src={mm_im1} className='mm-icon'/>
              </div>
              <h3>MTG Official Website</h3>
              <p>Learning the rules of MTG world to bring the most excited experience you play!</p>
            </Link>
          </div>
          <div className='mm-textbox'>
            <Link target="_blank" href="https://magic.wizards.com/en/mtgarena">
              <div className='mm-imbox'>
                <Image src={mm_im1} className='mm-icon'/>
              </div>
              <h3>MTG Arena</h3>
              <p>Learning the rules of MTG world to bring the most excited experience you play!</p>
            </Link>
          </div>
          <div className='mm-textbox'>
            <Link target="_blank" href="https://magic.wizards.com/en/products">
              <div className='mm-imbox'>
                <Image src={mm_im1} className='mm-icon'/>
              </div>
              <h3>Tabletop</h3>
              <p>Learning the rules of MTG world to bring the most excited experience you play!</p>
            </Link>
          </div>
          <div className='mm-textbox'>
            <Link target="_blank" href="https://www.mtgo.com/en/mtgo">
              <div className='mm-imbox'>
                <Image src={mm_im1} className='mm-icon'/>
              </div>
              <h3>Magic Online</h3>
              <p>Learning the rules of MTG world to bring the most excited experience you play!</p>
            </Link>
          </div>

      </div>
      <div className='cards-showcase'>
        <div className='csc-top'>
          <h1>Cards Showcase</h1>
        </div>
        <div className='csc-center'>
          <div className='csc-cards-show'>
            <div className='card-showbox'>
              <Link href={'/cards-library/card/Unholy-heat'}>
                <Card cardShowCase={true} disableHover={true} disableLink={true}/>
                <div className='csc-pop-text'>Most Users Acquired!</div>
              </Link>
            </div>
            <div className='card-showbox'>
              <Link href={'/cards-library/card/Unholy-heat'}>
                <Card cardShowCase={true} disableHover={true} disableLink={true}/>
                <div className='csc-pop-text'>Most Users Wanted!</div>
              </Link>
            </div>
            <div className='card-showbox'>
              <Link href={'/cards-library/card/Unholy-heat'}>
                <Card cardShowCase={true} disableHover={true} disableLink={true}/>
                <div className='csc-pop-text'>Most Users Request!</div>
              </Link>
            </div>
            <div className='card-showbox'>
              <Link href={'/cards-library/card/Unholy-heat'}>
                <Card cardShowCase={true} disableHover={true} disableLink={true}/>
                <div className='csc-pop-text'>Example Card!</div>
              </Link>
            </div>
          </div>
        </div>
        <div className='csc-bottom'></div>      
      </div>
      <div className='main-bottom'>
        <div className='main-bottom-im'></div>
        <div className='main-bottom-text'>
          <Link href={"/cards-library"}><h1>There are total over 20,000+ Unique Cards!</h1></Link>
        </div>
      </div>
    </>
  )
}
