import Head from 'next/head'
import SlidershowMain from '@/components/slideshow/slideshowMain'
import WhatIsMTGBody from '@/components/body_article/body_article'
import style from '@/components/body_article/body_article.module.css'
import Image from 'next/image'
import Link from 'next/link'
import MagicIm from '@/assets/magic_back.jpg'


export default function what_is_mtg() { 
  return (
    <>
      <Head>
        <title>What is MTG?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SlidershowMain text='What is MTG?'/>
      <WhatIsMTGBody text='Magic The Gathering'>
        <diiv className={style['ba-bc-content-secion']}>
          <div className={style['ba-bc-infobox']}><Image src={MagicIm} className={style['ba-mtg-im']}/></div>
            <div className={style['ba-bc-text-section']}>
              <p>Magic: The Gathering (colloquially known as Magic or MTG) is a tabletop and digital collectable card game created by Richard Garfield.Released in 1993 by Wizards of the Coast (now a subsidiary of Hasbro), Magic was the first trading card game and had approximately thirty-five million players as of December 2018, and over twenty billion Magic cards were produced in the period from 2008 to 2016, during which time it grew in popularity.</p>
              <p>A player in Magic takes the role of a Planeswalker, a powerful wizard who can travel ("walk") between dimensions ("planes") of the Multiverse, doing battle with other players as Planeswalkers by casting spells, using artifacts, and summoning creatures as depicted on individual cards drawn from their individual decks. A player defeats their opponent typically (but not always) by casting spells and attacking with creatures to deal damage to the opponent's "life total," with the objective being to reduce it from 20 to 0. Although the original concept of the game drew heavily from the motifs of traditional fantasy role-playing games such as Dungeons & Dragons, the gameplay bears little similarity to paper-and-pencil games, while simultaneously having substantially more cards and more complex rules than many other card games.</p>
            </div>
          </diiv>
          <p>Magic can be played by two or more players, either in person with printed cards or on a computer, smartphone or tablet with virtual cards through the Internet-based software Magic: The Gathering Online or other video games such as Magic: The Gathering Arena and Magic Duels. It can be played in various rule formats, which fall into two categories: constructed and limited. Limited formats involve players building a deck spontaneously out of a pool of random cards with a minimum deck size of 40 cards; in constructed formats, players create decks from cards they own, usually with a minimum of 60 cards per deck.</p>
          <div className={style['ba-bc-button-section']}>
            <input type="button" className='button-main' value={`Rule`}/>  
            <Link href={"/cards-library"}><input type="button" className='button-main' value={`Cards Library`}/></Link>
          </div>
      </WhatIsMTGBody>
    </>
  )
}